import type { Metadata } from 'next'
import './globals.css'
import { cn } from '@/lib/utils'
import { Providers } from '@/components/providers'

export const metadata: Metadata = {
  title: 'Next Startkit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={cn('font-sans')}>
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
