import type { Metadata } from 'next'
import './globals.css'
import { cn } from '@/lib/utils'
import { Providers } from '@/components/providers'
import { cookies } from 'next/headers'
import { AuthProvider } from '@/features/auth/ui/auth-provider'

export const metadata: Metadata = {
  title: 'Next Startkit',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const userCookie = cookieStore.get('user')?.value
  const user = userCookie ? JSON.parse(userCookie) : null

  return (
    <html lang="ko" className={cn('font-sans')}>
      <body className="antialiased">
        <AuthProvider user={user}>
          `<Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  )
}
